"""Pydantic schemas for structured data in the Content Generator system."""

from typing import List
from pydantic import BaseModel, Field


class SearchItem(BaseModel):
    """Represents a single web search to perform."""

    reason: str = Field(
        description="Explanation of why this search is important for the blog topic."
    )
    query: str = Field(
        description="The specific search term to use for web research."
    )


class SearchPlan(BaseModel):
    """Complete plan of web searches for a blog topic."""

    searches: List[SearchItem] = Field(
        description="List of web searches to perform for comprehensive research."
    )


class BlogContent(BaseModel):
    """Structured blog content generated by a writer agent."""

    title: str = Field(
        description="An engaging, SEO-friendly blog post title."
    )
    main_content: str = Field(
        description="The full blog post content in markdown format, comprehensive and well-structured."
    )
    summary: str = Field(
        description="A concise 2-3 sentence summary of the blog post for meta descriptions and previews."
    )


class BlogEvaluation(BaseModel):
    """Evaluation criteria for selecting the best blog content."""

    score: int = Field(
        description="Overall quality score from 1-10 based on content quality, engagement, and relevance.",
        ge=1,
        le=10
    )
    strengths: List[str] = Field(
        description="Key strengths of this blog content."
    )
    weaknesses: List[str] = Field(
        description="Areas for improvement in this blog content."
    )
    selected: bool = Field(
        description="Whether this content should be selected as the best option."
    )


class FormattedBlogPost(BaseModel):
    """Final formatted blog post ready for publishing."""

    title: str = Field(description="The blog post title.")
    meta_description: str = Field(description="SEO meta description.")
    slug: str = Field(description="URL-friendly slug for the blog post.")
    content: str = Field(description="Full HTML content of the blog post.")
    reading_time: int = Field(description="Estimated reading time in minutes.")
    tags: List[str] = Field(description="Relevant tags for categorization.")
    featured_image_alt: str = Field(description="Alt text for featured image.")


class ContentSafetyCheck(BaseModel):
    """Results of content safety evaluation."""

    is_safe: bool = Field(
        description="Whether the content passes safety checks."
    )
    issues_found: List[str] = Field(
        description="List of safety concerns or sensitive topics detected."
    )
    recommendations: List[str] = Field(
        description="Suggestions for making content safer if issues are found."
    )


class MediumBlogContent(BaseModel):
    """Structured blog content optimized for Medium articles."""

    title: str = Field(
        description="Compelling, benefit-driven title for Medium."
    )
    subtitle: str = Field(
        description="Context-adding subtitle that intrigues without giving everything away."
    )
    hook: str = Field(
        description="Engaging opening (1-3 paragraphs) with story, statistic, or bold statement."
    )
    preview: str = Field(
        description="Clear promise of what readers will learn or gain."
    )
    sections_content: str = Field(
        description="Main content broken into 3-7 clear sections with descriptive headers. Use **H2:** for section headers and **PULL_QUOTE:** for pull quotes."
    )
    conclusion: str = Field(
        description="Strong conclusion with key takeaways (2-3 main points)."
    )
    call_to_action: str = Field(
        description="Inspiring call-to-action, thought-provoking question, or final value-add."
    )
    structure_type: str = Field(
        description="Article structure type: '3-act', 'how-to', 'listicle', or 'general'."
    )
    target_word_count: int = Field(
        default=1700,
        description="Target word count for 7-10 minute read (typically 1400-2000)."
    )


class MediumStructureValidation(BaseModel):
    """Results of Medium structure validation."""

    is_medium_optimized: bool = Field(
        description="Whether the content follows Medium best practices."
    )
    hook_score: int = Field(
        description="Hook effectiveness score (1-10).",
        ge=1,
        le=10
    )
    structure_score: int = Field(
        description="Structure compliance score (1-10).",
        ge=1,
        le=10
    )
    engagement_score: int = Field(
        description="Engagement elements score (1-10).",
        ge=1,
        le=10
    )
    length_score: int = Field(
        description="Length optimization score (1-10).",
        ge=1,
        le=10
    )
    issues_found: List[str] = Field(
        default_factory=list,
        description="List of Medium structure issues detected."
    )
    recommendations: List[str] = Field(
        default_factory=list,
        description="Suggestions for improving Medium optimization."
    )
    overall_score: int = Field(
        description="Overall Medium optimization score (1-10).",
        ge=1,
        le=10
    )
