#!/usr/bin/env python3
"""
Setup script for Content Generator
Helps users set up their environment variables and get started quickly.
"""

import os
import sys
from pathlib import Path

def setup_environment():
    """Interactive setup for environment variables."""
    print("🚀 Content Generator Setup")
    print("=" * 40)

    project_dir = Path(__file__).parent
    env_file = project_dir / '.env'

    if env_file.exists():
        response = input("⚠️  .env file already exists. Overwrite? (y/N): ").lower().strip()
        if response not in ['y', 'yes']:
            print("Setup cancelled.")
            return

    print("\n📝 Setting up environment variables...")
    print("You'll need an OpenAI API key from: https://platform.openai.com/api-keys")

    api_key = input("\nEnter your OpenAI API key (sk-...): ").strip()

    if not api_key.startswith('sk-'):
        print("❌ API key should start with 'sk-'. Please check and try again.")
        return

    # Create .env file
    env_content = f"""# Content Generator Environment Variables
# Auto-generated by setup.py

# OpenAI API Key
OPENAI_API_KEY={api_key}

# Optional: Alternative AI providers
# GOOGLE_API_KEY=your-google-api-key
# DEEPSEEK_API_KEY=your-deepseek-api-key
# GROQ_API_KEY=your-groq-api-key

# Optional: Email service
# SENDGRID_API_KEY=your-sendgrid-api-key

# Optional: Tracing and monitoring
# OPENAI_TRACING_ENABLED=true
"""

    try:
        with open(env_file, 'w') as f:
            f.write(env_content)
        print(f"✅ Created .env file at: {env_file}")

        # Set file permissions to be readable only by owner (security)
        os.chmod(env_file, 0o600)
        print("🔒 Set secure permissions on .env file")

    except Exception as e:
        print(f"❌ Error creating .env file: {e}")
        return

    print("\n🎉 Setup complete!")
    print("\nNext steps:")
    print("1. Run: python app.py")
    print("2. Open your browser to: http://localhost:7860")
    print("3. Start generating blogs!")

def main():
    """Main setup function."""
    if len(sys.argv) > 1 and sys.argv[1] == '--help':
        print("Content Generator Setup Script")
        print("Usage: python setup.py")
        print("This script will help you set up your environment variables.")
        return

    setup_environment()

if __name__ == "__main__":
    main()
